# Generated by Django 5.2.3 on 2025-07-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.faculty')),
            ],
        ),
    ]
