# Generated by Django 5.2.3 on 2025-07-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultySubject',
        ),
    ]
