# Generated by Django 5.2.3 on 2025-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_facultysubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
