# Generated by Django 5.2.3 on 2025-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_login_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='fname',
        ),
        migrations.AddField(
            model_name='faculty',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
