# Generated by Django 5.2.3 on 2025-07-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_login_fname_faculty_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sem',
            new_name='semester',
        ),
    ]
