# Generated by Django 5.2.3 on 2025-07-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
