# Generated by Django 5.2.3 on 2025-07-09 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_certificate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdetailsdash.classsection')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdetailsdash.requirement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdetailsdash.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdetailsdash.classsection')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdetailsdash.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdetailsdash.subject'),
        ),
    ]
