# Generated by Django 5.2.3 on 2025-07-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_login_fname_faculty_fname'),
        ('facultydash', '0001_initial'),
        ('fdetailsdash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentrequirement',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='studentrequirement',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentRequirementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('faculty_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultydash.facultysubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('student', 'faculty_subject', 'requirement_type')},
            },
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentRequirement',
        ),
    ]
