# Generated by Django 5.2.3 on 2025-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdetailsdash', '0003_studentrequirementstatus_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequirementstatus',
            name='hard_copy_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentrequirementstatus',
            name='hard_copy_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentrequirementstatus',
            name='soft_copy_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/soft/'),
        ),
        migrations.AddField(
            model_name='studentrequirementstatus',
            name='soft_copy_required',
            field=models.BooleanField(default=False),
        ),
    ]
